install:
	if [ ! -f "${HOME}/.local/bin/diff-dir" ]; then ln -s `pwd`/diff-dir.py ${HOME}/.local/bin/diff-dir; fi;
	if [ ! -f "${HOME}/.local/bin/ftime" ]; then ln -s `pwd`/ftime.py ${HOME}/.local/bin/ftime; fi;
	if [ ! -f "${HOME}/.local/bin/getpics" ]; then ln -s `pwd`/getpics.py ${HOME}/.local/bin/getpics; fi;
	if [ ! -f "${HOME}/.local/bin/decrypt" ]; then ln -s `pwd`/decrypt.py ${HOME}/.local/bin/decrypt; fi;
	if [ ! -f "${HOME}/.local/bin/fdump" ]; then ln -s `pwd`/fdump.py ${HOME}/.local/bin/fdump; fi;
	if [ ! -f "${HOME}/.local/bin/cpscreenshot" ]; then ln -s `pwd`/cpscreenshot.py ${HOME}/.local/bin/cpscreenshot; fi;
	if [ ! -f "${HOME}/.local/bin/cpdownload" ]; then ln -s `pwd`/cpdownload.py ${HOME}/.local/bin/cpdownload; fi;
	if [ ! -f "${HOME}/.local/bin/mvscreenshot" ]; then ln -s `pwd`/mvscreenshot.py ${HOME}/.local/bin/mvscreenshot; fi;
	if [ ! -f "${HOME}/.local/bin/cpdownload" ]; then ln -s `pwd`/cpdownload.py ${HOME}/.local/bin/cpdownload; fi;
	if [ ! -f "${HOME}/.local/bin/searchbin" ]; then ln -s `pwd`/searchbin.py ${HOME}/.local/bin/searchbin; fi;
	if [ ! -f "${HOME}/.local/bin/replace_in_files" ]; then ln -s `pwd`/replace_in_files.py ${HOME}/.local/bin/replace_in_files; fi;
	if [ ! -f "${HOME}/.local/bin/blog" ]; then ln -s `pwd`/blog.py ${HOME}/.local/bin/blog; fi;
	if [ ! -f "${HOME}/.local/bin/til" ]; then ln -s `pwd`/til.py ${HOME}/.local/bin/til; fi;
	if [ ! -f "${HOME}/.local/bin/threads" ]; then ln -s `pwd`/threads.py ${HOME}/.local/bin/threads; fi;
	if [ ! -f "${HOME}/.local/bin/vimmv" ]; then ln -s `pwd`/vimmv.py ${HOME}/.local/bin/vimmv; fi;
	if [ ! -f "${HOME}/.local/bin/pyleetcode" ]; then ln -s `pwd`/pyleetcode.py ${HOME}/.local/bin/pyleetcode; fi;
	if [ ! -f "${HOME}/.local/bin/pyquick" ]; then ln -s `pwd`/pyquick.py ${HOME}/.local/bin/pyquick; fi;
	if [ ! -f "${HOME}/.local/bin/pytimeit" ]; then ln -s `pwd`/pytimeit.py ${HOME}/.local/bin/pytimeit; fi;
	if [ ! -f "${HOME}/.local/bin/ctimeit" ]; then ln -s `pwd`/ctimeit.py ${HOME}/.local/bin/ctimeit; fi;
	if [ ! -f "${HOME}/.local/bin/md2html" ]; then ln -s `pwd`/md2html.py ${HOME}/.local/bin/md2html; fi;
	if [ ! -f "${HOME}/.local/bin/ftags" ]; then ln -s `pwd`/ftags.py ${HOME}/.local/bin/ftags; fi;
	if [ ! -f "${HOME}/.local/bin/mdtags" ]; then ln -s `pwd`/mdtags.py ${HOME}/.local/bin/mdtags; fi;
	if [ ! -f "${HOME}/.local/bin/disassemble" ]; then ln -s `pwd`/disassemble.py ${HOME}/.local/bin/disassemble; fi;
	if [ ! -f "${HOME}/.local/bin/kb" ]; then ln -s `pwd`/kb.py ${HOME}/.local/bin/kb; fi;
	if [ ! -f "${HOME}/.local/bin/kbfltk" ]; then ln -s `pwd`/kbfltk.py ${HOME}/.local/bin/kbfltk; fi;
	if [ ! -f "${HOME}/.local/bin/pyputprints" ]; then ln -s `pwd`/pyputprints.py ${HOME}/.local/bin/pyputprints; fi;
	if [ ! -f "${HOME}/.local/bin/openpickle" ]; then ln -s `pwd`/openpickle.py ${HOME}/.local/bin/openpickle; fi;
	if [ ! -f "${HOME}/.local/bin/git-conflict-marker-split" ]; then ln -s `pwd`/git-conflict-marker-split.py ${HOME}/.local/bin/git-conflict-marker-split; fi;
	if [ ! -f "${HOME}/.local/bin/lslog" ]; then ln -s `pwd`/lslog.py ${HOME}/.local/bin/lslog; fi;
	if [ ! -f "${HOME}/.local/bin/makeurl" ]; then ln -s `pwd`/makeurl.py ${HOME}/.local/bin/makeurl; fi;
	if [ ! -f "${HOME}/.local/bin/grepbin" ]; then ln -s `pwd`/grepbin.py ${HOME}/.local/bin/grepbin; fi;
	if [ ! -f "${HOME}/.local/bin/binja-dis" ]; then ln -s `pwd`/binja-dis.py ${HOME}/.local/bin/binja-dis; fi;
	if [ ! -f "${HOME}/.local/bin/binja-tlinfo" ]; then ln -s `pwd`/binja-tlinfo.py ${HOME}/.local/bin/binja-tlinfo; fi;
	if [ ! -f "${HOME}/.local/bin/binja-cfg-mermaid" ]; then ln -s `pwd`/binja-cfg-mermaid.py ${HOME}/.local/bin/binja-cfg-mermaid; fi;
	if [ ! -f "${HOME}/.local/bin/binja-cfg-dot" ]; then ln -s `pwd`/binja-cfg-dot.py ${HOME}/.local/bin/binja-cfg-dot; fi;
	if [ ! -f "${HOME}/.local/bin/binja-rip" ]; then ln -s `pwd`/binja-rip.py ${HOME}/.local/bin/binja-rip; fi;
	if [ ! -f "${HOME}/.local/bin/bencode2json" ]; then ln -s `pwd`/bencode2json.py ${HOME}/.local/bin/bencode2json; fi;
	if [ ! -f "${HOME}/.local/bin/ls2markdown" ]; then ln -s `pwd`/ls2markdown.py ${HOME}/.local/bin/ls2markdown; fi;
	if [ ! -f "${HOME}/.local/bin/daily" ]; then ln -s `pwd`/daily.py ${HOME}/.local/bin/daily; fi;
	if [ ! -f "${HOME}/.local/bin/comsplit" ]; then ln -s `pwd`/comsplit.py ${HOME}/.local/bin/comsplit; fi;
	if [ ! -f "${HOME}/.local/bin/commerge" ]; then ln -s `pwd`/commerge.py ${HOME}/.local/bin/commerge; fi;
	if [ ! -f "${HOME}/.local/bin/showargs" ]; then ln -s `pwd`/showargs.py ${HOME}/.local/bin/showargs; fi;
	if [ ! -f "${HOME}/.local/bin/gen-guid" ]; then ln -s `pwd`/gen-guid.py ${HOME}/.local/bin/gen-guid; fi;
	if [ ! -f "${HOME}/.local/bin/journal" ]; then ln -s `pwd`/journal.py ${HOME}/.local/bin/journal; fi;
	if [ ! -f "${HOME}/.local/bin/set_time_exif" ]; then ln -s `pwd`/set_time_exif.py ${HOME}/.local/bin/set_time_exif; fi;
	if [ ! -f "${HOME}/.local/bin/set_time_git" ]; then ln -s `pwd`/set_time_git.py ${HOME}/.local/bin/set_time_git; fi;
	if [ ! -f "${HOME}/.local/bin/dhcpserver" ]; then ln -s `pwd`/dhcpserver.py ${HOME}/.local/bin/dhcpserver; fi;
	if [ ! -f "${HOME}/.local/bin/torrent_dump" ]; then ln -s `pwd`/torrent_dump.py ${HOME}/.local/bin/torrent_dump; fi;

uninstall:
	if [ -f "${HOME}/.local/bin/diff-dir" ]; then rm ${HOME}/.local/bin/diff-dir; fi;
	if [ -f "${HOME}/.local/bin/ftime" ]; then rm ${HOME}/.local/bin/ftime; fi;
	if [ -f "${HOME}/.local/bin/getpics" ]; then rm ${HOME}/.local/bin/getpics; fi;
	if [ -f "${HOME}/.local/bin/decrypt" ]; then rm ${HOME}/.local/bin/decrypt; fi;
	if [ -f "${HOME}/.local/bin/fdump" ]; then rm ${HOME}/.local/bin/fdump; fi;
	if [ -f "${HOME}/.local/bin/cpscreenshot" ]; then rm ${HOME}/.local/bin/cpscreenshot; fi;
	if [ -f "${HOME}/.local/bin/cpdownload" ]; then rm ${HOME}/.local/bin/cpdownload; fi;
	if [ -f "${HOME}/.local/bin/mvscreenshot" ]; then rm ${HOME}/.local/bin/mvscreenshot; fi;
	if [ -f "${HOME}/.local/bin/cpdownload" ]; then rm ${HOME}/.local/bin/cpdownload; fi;
	if [ -f "${HOME}/.local/bin/searchbin" ]; then rm ${HOME}/.local/bin/searchbin; fi;
	if [ -f "${HOME}/.local/bin/replace_in_files" ]; then rm ${HOME}/.local/bin/replace_in_files; fi;
	if [ -f "${HOME}/.local/bin/blog" ]; then rm ${HOME}/.local/bin/blog; fi;
	if [ -f "${HOME}/.local/bin/til" ]; then rm ${HOME}/.local/bin/til; fi;
	if [ -f "${HOME}/.local/bin/threads" ]; then rm ${HOME}/.local/bin/threads; fi;
	if [ -f "${HOME}/.local/bin/vimmv" ]; then rm ${HOME}/.local/bin/vimmv; fi;
	if [ -f "${HOME}/.local/bin/pyleetcode" ]; then rm ${HOME}/.local/bin/pyleetcode; fi;
	if [ -f "${HOME}/.local/bin/pyquick" ]; then rm ${HOME}/.local/bin/pyquick; fi;
	if [ -f "${HOME}/.local/bin/pytimeit" ]; then rm ${HOME}/.local/bin/pytimeit; fi;
	if [ -f "${HOME}/.local/bin/ctimeit" ]; then rm ${HOME}/.local/bin/ctimeit; fi;
	if [ -f "${HOME}/.local/bin/md2html" ]; then rm ${HOME}/.local/bin/md2html; fi;
	if [ -f "${HOME}/.local/bin/ftags" ]; then rm ${HOME}/.local/bin/ftags; fi;
	if [ -f "${HOME}/.local/bin/mdtags" ]; then rm ${HOME}/.local/bin/mdtags; fi;
	if [ -f "${HOME}/.local/bin/disassemble" ]; then rm ${HOME}/.local/bin/disassemble; fi;
	if [ -f "${HOME}/.local/bin/kb" ]; then rm ${HOME}/.local/bin/kb; fi;
	if [ -f "${HOME}/.local/bin/kbfltk" ]; then rm ${HOME}/.local/bin/kbfltk; fi;
	if [ -f "${HOME}/.local/bin/pyputprints" ]; then rm ${HOME}/.local/bin/pyputprints; fi;
	if [ -f "${HOME}/.local/bin/openpickle" ]; then rm ${HOME}/.local/bin/openpickle; fi;
	if [ -f "${HOME}/.local/bin/git-conflict-marker-split" ]; then rm ${HOME}/.local/bin/git-conflict-marker-split; fi;
	if [ -f "${HOME}/.local/bin/lslog" ]; then rm ${HOME}/.local/bin/lslog; fi;
	if [ -f "${HOME}/.local/bin/makeurl" ]; then rm ${HOME}/.local/bin/makeurl; fi;
	if [ -f "${HOME}/.local/bin/grepbin" ]; then rm ${HOME}/.local/bin/grepbin; fi;
	if [ -f "${HOME}/.local/bin/binja-dis" ]; then rm ${HOME}/.local/bin/binja-dis; fi;
	if [ -f "${HOME}/.local/bin/binja-tlinfo" ]; then rm ${HOME}/.local/bin/binja-tlinfo; fi;
	if [ -f "${HOME}/.local/bin/binja-cfg-mermaid" ]; then rm ${HOME}/.local/bin/binja-cfg-mermaid; fi;
	if [ -f "${HOME}/.local/bin/binja-cfg-dot" ]; then rm ${HOME}/.local/bin/binja-cfg-dot; fi;
	if [ -f "${HOME}/.local/bin/binja-rip" ]; then rm ${HOME}/.local/bin/binja-rip; fi;
	if [ -f "${HOME}/.local/bin/bencode2json" ]; then rm ${HOME}/.local/bin/bencode2json; fi;
	if [ -f "${HOME}/.local/bin/ls2markdown" ]; then rm ${HOME}/.local/bin/ls2markdown; fi;
	if [ -f "${HOME}/.local/bin/daily" ]; then rm ${HOME}/.local/bin/daily; fi;
	if [ -f "${HOME}/.local/bin/comsplit" ]; then rm ${HOME}/.local/bin/comsplit; fi;
	if [ -f "${HOME}/.local/bin/commerge" ]; then rm ${HOME}/.local/bin/commerge; fi;
	if [ -f "${HOME}/.local/bin/showargs" ]; then rm ${HOME}/.local/bin/showargs; fi;
	if [ -f "${HOME}/.local/bin/gen-guid" ]; then rm ${HOME}/.local/bin/gen-guid; fi;
	if [ -f "${HOME}/.local/bin/journal" ]; then rm ${HOME}/.local/bin/journal; fi;
	if [ -f "${HOME}/.local/bin/set_time_exif" ]; then rm ${HOME}/.local/bin/set_time_exif; fi;
	if [ -f "${HOME}/.local/bin/set_time_git" ]; then rm ${HOME}/.local/bin/set_time_git; fi;
	if [ -f "${HOME}/.local/bin/dhcpserver" ]; then rm ${HOME}/.local/bin/dhcpserver; fi;
	if [ -f "${HOME}/.local/bin/torrent_dump" ]; then rm ${HOME}/.local/bin/torrent_dump; fi;
