// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef Gui_h
#define Gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Input.H>

class Gui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *w;
  Fl_Text_Editor *body;
  Fl_Input *regex;
private:
  inline void cb_regex_i(Fl_Input*, void*);
  static void cb_regex(Fl_Input*, void*);
};
int main(int ac, char **av);
#endif
