
install:
	if [ ! -f "/usr/local/bin/ftime" ]; then ln -s `pwd`/ftime.py /usr/local/bin/ftime; fi;
	if [ ! -f "/usr/local/bin/getpics" ]; then ln -s `pwd`/getpics.py /usr/local/bin/getpics; fi;
	if [ ! -f "/usr/local/bin/decrypt" ]; then ln -s `pwd`/decrypt.py /usr/local/bin/decrypt; fi;
	if [ ! -f "/usr/local/bin/fdump" ]; then ln -s `pwd`/fdump.py /usr/local/bin/fdump; fi;
	if [ ! -f "/usr/local/bin/cpscreenshot" ]; then ln -s `pwd`/cpscreenshot.py /usr/local/bin/cpscreenshot; fi;
	if [ ! -f "/usr/local/bin/cpdownload" ]; then ln -s `pwd`/cpdownload.py /usr/local/bin/cpdownload; fi;
	if [ ! -f "/usr/local/bin/searchbin" ]; then ln -s `pwd`/searchbin.py /usr/local/bin/searchbin; fi;
	if [ ! -f "/usr/local/bin/replace_in_files" ]; then ln -s `pwd`/replace_in_files.py /usr/local/bin/replace_in_files; fi;
	if [ ! -f "/usr/local/bin/blog" ]; then ln -s `pwd`/blog.py /usr/local/bin/blog; fi;
	if [ ! -f "/usr/local/bin/disthumb" ]; then ln -s `pwd`/disthumb.py /usr/local/bin/disthumb; fi;

uninstall:
	rm /usr/local/bin/ftime
	rm /usr/local/bin/getpics
	rm /usr/local/bin/decrypt
	rm /usr/local/bin/fdump
	rm /usr/local/bin/cpscreenshot
	rm /usr/local/bin/cpdownload
	rm /usr/local/bin/searchbin
	rm /usr/local/bin/replace_in_files
	rm /usr/local/bin/blog
	rm /usr/local/bin/disthumb
