install:
	ln -s `pwd`/ftime.py /usr/local/bin/ftime
	ln -s `pwd`/getpics.py /usr/local/bin/getpics
	ln -s `pwd`/decrypt.py /usr/local/bin/decrypt
	ln -s `pwd`/fdump.py /usr/local/bin/fdump
	ln -s `pwd`/cpscreenshot.py /usr/local/bin/cpscreenshot
	ln -s `pwd`/cpdownload.py /usr/local/bin/cpdownload
	ln -s `pwd`/searchbin.py /usr/local/bin/searchbin
	ln -s `pwd`/replace_in_files.py /usr/local/bin/replace_in_files
	ln -s `pwd`/blog.py /usr/local/bin/blog

uninstall:
	rm /usr/local/bin/ftime
	rm /usr/local/bin/getpics
	rm /usr/local/bin/decrypt
	rm /usr/local/bin/fdump
	rm /usr/local/bin/cpscreenshot
	rm /usr/local/bin/cpdownload
	rm /usr/local/bin/searchbin
	rm /usr/local/bin/replace_in_files
	rm /usr/local/bin/blog
