install:
	ln -s `pwd`/ftime.py /usr/local/bin/ftime
	ln -s `pwd`/getpics.py /usr/local/bin/getpics
	ln -s `pwd`/decrypt.py /usr/local/bin/decrypt
	ln -s `pwd`/lstags.py /usr/local/bin/lstags
	ln -s `pwd`/cpscreenshot.py /usr/local/bin/cpscreenshot

uninstall:
	rm /usr/local/bin/ftime
	rm /usr/local/bin/getpics
	rm /usr/local/bin/decrypt
	rm /usr/local/bin/lstags
	rm /usr/local/bin/cpscreenshot
