// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef Gui_h
#define Gui_h
#include <FL/Fl.H>
#include "DndImage.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>

class Gui {
public:
  Fl_Double_Window* make_window();
  Fl_Tabs *tabs;
  Fl_Group *tabResize;
  Fl_Value_Input *resizeWidth;
private:
  inline void cb_resizeWidth_i(Fl_Value_Input*, void*);
  static void cb_resizeWidth(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *resizeHeight;
private:
  inline void cb_resizeHeight_i(Fl_Value_Input*, void*);
  static void cb_resizeHeight(Fl_Value_Input*, void*);
public:
  Fl_Button *resizeBtnSave;
private:
  inline void cb_resizeBtnSave_i(Fl_Button*, void*);
  static void cb_resizeBtnSave(Fl_Button*, void*);
  inline void cb_Original_i(Fl_Button*, void*);
  static void cb_Original(Fl_Button*, void*);
public:
  Fl_Round_Button *btnCenter;
private:
  inline void cb_btnCenter_i(Fl_Round_Button*, void*);
  static void cb_btnCenter(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *btnCorner;
private:
  inline void cb_btnCorner_i(Fl_Round_Button*, void*);
  static void cb_btnCorner(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *btnStretchEW;
private:
  inline void cb_btnStretchEW_i(Fl_Round_Button*, void*);
  static void cb_btnStretchEW(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *btnStretchNS;
private:
  inline void cb_btnStretchNS_i(Fl_Round_Button*, void*);
  static void cb_btnStretchNS(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *btnFill;
private:
  inline void cb_btnFill_i(Fl_Round_Button*, void*);
  static void cb_btnFill(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *btnClip;
private:
  inline void cb_btnClip_i(Fl_Round_Button*, void*);
  static void cb_btnClip(Fl_Round_Button*, void*);
  inline void cb_1024x768_i(Fl_Button*, void*);
  static void cb_1024x768(Fl_Button*, void*);
  inline void cb_640x480_i(Fl_Button*, void*);
  static void cb_640x480(Fl_Button*, void*);
  inline void cb_640x360_i(Fl_Button*, void*);
  static void cb_640x360(Fl_Button*, void*);
  inline void cb_960x540_i(Fl_Button*, void*);
  static void cb_960x540(Fl_Button*, void*);
  inline void cb_1920x1080_i(Fl_Button*, void*);
  static void cb_1920x1080(Fl_Button*, void*);
  inline void cb_320x180_i(Fl_Button*, void*);
  static void cb_320x180(Fl_Button*, void*);
public:
  DndImage *resizeImg;
  Fl_Output *fpathIn;
  Fl_Choice *interpMethods;
  Fl_Input *fpathOut;
};
int main(int ac, char **av);
#endif
