// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "Gui.h"
#include "logic.h"

Fl_Double_Window* Gui::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1042, 831, "fastimg");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 1040, 828);
      { Fl_Group* o = new Fl_Group(0, 21, 1034, 755, "Resize");
        { resizeWidth = new Fl_Value_Input(49, 28, 41, 20, "width:");
          resizeWidth->value(1024);
        } // Fl_Value_Input* resizeWidth
        { resizeHeight = new Fl_Value_Input(140, 28, 41, 21, "height:");
          resizeHeight->value(768);
        } // Fl_Value_Input* resizeHeight
        { resizeBtnSave = new Fl_Button(191, 28, 63, 20, "Save");
        } // Fl_Button* resizeBtnSave
        { resizeBtnSaveAs = new Fl_Button(264, 28, 63, 20, "Save As");
        } // Fl_Button* resizeBtnSaveAs
        { resizeImg = new DndImage(10, 56, 1024, 720);
          resizeImg->box(FL_NO_BOX);
          resizeImg->color(FL_BACKGROUND_COLOR);
          resizeImg->selection_color(FL_BACKGROUND_COLOR);
          resizeImg->labeltype(FL_NORMAL_LABEL);
          resizeImg->labelfont(0);
          resizeImg->labelsize(14);
          resizeImg->labelcolor(FL_FOREGROUND_COLOR);
          resizeImg->align(Fl_Align(FL_ALIGN_CENTER));
          resizeImg->when(FL_WHEN_RELEASE);
        } // DndImage* resizeImg
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(4, 25, 644, 359, "2x2");
        o->hide();
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(12, 33, 1028, 795, "4x4");
        o->hide();
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

int main(int ac, char **av) {
  Gui gui;
  Fl_Double_Window *w = gui.make_window();
  onGuiInit(&gui);
  w->end();
  w->show();
  int rc = Fl::run();
  onGuiExit(rc);
  return rc;
}
